### ISSUE TITLE
Add LICENSE?

### ISSUE THREAD

**Issue by stes** [GrantCuster/umap-explorer#2]
Hi @GrantCuster , great demo!

It seems like the code is currently released under [No License](https://choosealicense.com/no-permission/). Could you clarify if this is on purpose? Otherwise, do you think it would be possible to add a `LICENSE` if you intend to make this an open source release?

**Comment by GrantCuster** [comment]
Thanks, yes, just added the MIT license to it.

**Comment by stes** [comment]
Great, thanks a lot!
